fastlane_version "2.68.2"

default_platform :ios

platform :ios do

  lane :setup do
    cocoapods
    Dir.chdir ".." do
     sh("Scripts/generate_proto.py")
   end
  end

  lane :beta do |options|
    import("./CommonFastfile")
    common_beta(options)
  end

  lane :notify do
    import("./CommonFastfile")
    notify_changes()
  end

  lane :gt do
    import("./CommonFastfile")
    getTeamNames()
  end

  # fastlane action new_version bump_type:patch|minor|major
  lane :new_version do |options|
    import("./CommonFastfile")
    bump_type = options[:bump_type] ? options[:bump_type] : "patch"
    increment_and_push(bump_type: bump_type)
  end

  lane :lok do 
    lokalise_upload(
      api_token: "a0cb36d3ab033b32ffeb6dad19e65d0272cf56de",
      project_identifier: "735240135c051242886fb6.14689237",
      source: "./Fitness/Supporting Files/",
      languages: ["en"]
    )
    lokalise(
      api_token: "a0cb36d3ab033b32ffeb6dad19e65d0272cf56de",
      project_identifier: "735240135c051242886fb6.14689237",
      destination: "./Fitness/Supporting Files/"
    )
  end

end

